#!/bin/bash

DB_NAME="pi"
DB_USER="guo95132"   #guo95132          #pi
DB_HOST="localhost"   #localhost  #qa3
DB_PORT="5432"  
DB_PASSWORD="Welc0me123"
export PGPASSWORD=$DB_PASSWORD

TABLE_NAME="OTA_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats,  
                        Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes, MinT, MaxT, AvgT, FailedNum, RecvrNum)"
VALUES="('rls-v02_00_03-9b5d04e', 'O2', 'self', 'qa7', 'MGM2423A2US0C1950', 57, 12, 18, 1, 1, 0, '~2.5hrs', 30, '', false, '', false, '', false, './O2_ota_self_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/ota/run_ota_3D.py', '', '', 224, 270, 247, 0, 0)"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="POWER_DURING_OTA_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('rls-v02_00_03-9b5d04e', 'O2', 'qa6', 'MG32401A2US100199', 57, 11, 17, 20, 20, 0, '~1.5hrs', 1, '', false, '', false, '', false, './O2_ota_power_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/ota/testsuites/ota_power_cycles.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="OTA_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats,  
                        Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes, MinT, MaxT, AvgT, FailedNum, RecvrNum)"
VALUES="('rls-v02_00_03-9b5d04e', 'O2', 'intFTUG', 'qa7', 'MGM2420A2US0C0248', 57, 12, 18, 2, 2, 0, '~5hrs', 30, '', false, '', false, '', false, './O2_ota_int_upgrade_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/ota/run_ota_3D.py', '', '', 280, 594, 298, 0, 0)"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="OTA_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats,  
                        Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes, MinT, MaxT, AvgT, FailedNum, RecvrNum)"
VALUES="('rls-v02_00_03-9b5d04e', 'O2', 'extFTUG', 'qa7', 'MGM2423A2US0C1950', 57, 12, 18, 2, 2, 0, '~4.5hrs', 30, '', false, '', false, '', false, './O2_ota_ext_upgrade_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/ota/run_ota_3D.py', '', '', 230, 371, 264, 0, 0)"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="OTA_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats,  
                        Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes, MinT, MaxT, AvgT, FailedNum, RecvrNum)"
VALUES="('rls-v02_00_03-9b5d04e', 'O2', 'prodUG', 'qa7', 'MGM2423A2US0C1950', 57, 12, 18, 2, 2, 0, '~4hrs', 30, '', false, '', false, '', false, './O2_ota_prod_upgrade_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/ota/run_ota_3D.py', '', '', 214, 357, 232, 0, 0)"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_OP_PR_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'idle', 'qa9', 'MG32401A2US100204', 57, 16, 22, 26, 26, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_dgo_idle_op_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_testsuite_IDLE_5hr_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_OP_PR_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'lip', 'qa9', 'MG32401A2US100204', 57, 16, 22, 28, 28, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_dgo_lip_op_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_testsuite_LIP_5hr_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_OP_PR_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'hip', 'qa9', 'MG32401A2US100204', 57, 16, 22, 25, 25, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_dgo_hip_op_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_testsuite_HIP_5hr_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_OP_PR_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'cooldown', 'qa9', 'MG32401A2US100204', 57, 16, 22, 28, 28, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_dgo_cooldown_op_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_testsuite_COOLDOWN_5hr_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_OP_PR_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'fluff', 'qa9', 'MG32401A2US100204', 57, 16, 22, 50, 50, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_dgo_fluff_op_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_testsuite_FLUFF_5hr_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_ADD_MASS_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'idle', 'qa9', 'MG32401A2US100204', 57, 16, 22, 15, 15, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_dgo_idle_mass_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_mass_add_5hr_min_runtime_IDLE_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_ADD_MASS_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'lip', 'qa9', 'MG32401A2US100204', 57, 16, 22, 15, 15, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_dgo_lip_mass_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_mass_add_5hr_min_runtime_LIP_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_ADD_MASS_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'hip', 'qa9', 'MG32401A2US100204', 57, 16, 22, 15, 15, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_dgo_hip_mass_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_mass_add_5hr_min_runtime_HIP_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_ADD_MASS_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'cooldown', 'qa9', 'MG32401A2US100204', 57, 16, 22, 15, 15, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_dgo_cooldown_mass_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_mass_add_5hr_min_runtime_COOLDOWN_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="DGO_ADD_MASS_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'fluff', 'qa9', 'MG32401A2US100204', 57, 16, 22, 15, 15, 0, '~1.5hrs', 1, '', false, '', false, '', false, './O2_dgo_fluff_mass_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_mass_add_5hr_min_runtime_FLUFF_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="EEPROM_STRESS_TEST_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'qa9', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~1hrs', 100, '', false, '', false, '', false, './O2_eeprom_stress_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/eeprom_stress_test.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="PAIRING_WITHOUT_BLE_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'home_O2', 'MG22335A2US0024', 57, 14, 20, 104, 104, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_pairing_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/pairing/testsuites/pairing_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="START_VIA_BIN_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'normal', 'qa9', 'MG32401A2US100204', 57, 16, 22, 46, 46, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_start_via_bin_B_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_start_via_bin_B_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="START_VIA_BIN_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'stress', 'qa9', 'MG32401A2US100204', 57, 16, 22, 21, 21, 0, '~1.5hrs', 30, '', false, '', false, '', false, './O2_start_via_bin_A_stress_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_start_via_bin_stress_A_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="CHILD_LOCK_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'normal', 'qa9', 'MG32401A2US100204', 57, 16, 22, 91, 91, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_child_lock_B_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/child_lock_B_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="CHILD_LOCK_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'stress', 'qa9', 'MG32401A2US100204', 57, 16, 22, 19, 19, 0, '~1hrs', 30, '', false, '', false, '', false, './O2_child_lock_A_stress_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/child_lock_stress_A_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="SAFETY_TEST_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)"
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'qa9', 'MG32401A2US100204', 57, 16, 22, 42, 0, 0, '0', 0, '', false, '', false, '', false, '', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/safety_test_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BOOT_CYCLE_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, TestType, SvrName, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'stress', 'qa9', 'MG32401A2US100204', 57, 16, 22, 17, 17, 0, '~5hrs', 30, '', false, '', false, '', false, './O2_boot_cycle_A_stress_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/more/testsuites/dgo_test_boot_cycle.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="SMOKE_TEST_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'qa9', 'pairing', 'MG32401A2US100204', 57, 16, 22, 11, 11, 0, '~0.5hrs', 3, '', false, '', false, '', false, './O2_smoke_pairing_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/pairing/testsuites/wifi_test_O2_automation.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="SMOKE_TEST_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'qa9', 'dgo_inactive', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 3, '', false, '', false, '', false, './O2_smoke_dgo_inactive_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_inactive.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="SMOKE_TEST_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'qa9', 'test_lid', 'MG32401A2US100204', 57, 16, 22, 18, 18, 0, '~0.5hrs', 3, '', false, '', false, '', false, './O2_smoke_test_lid_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/lid_lock_smoke.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'hip', 'qa9', 'add_mass_hip', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_add_mass_hip_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_add_mass_hip.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'hip', 'qa9', 'reset_hip', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_reset_hip_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_reset_hip.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'sht40_calibration', 'MG32401A2US100204', 57, 16, 22, 12, 12, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_sht40_calibration_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_sht40_calibration.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'sht40_cal_skip_when_hot', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_sht40_cal_skip_when_hot_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_sht40_cal_skip_when_hot.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'start_stop_no_vacation', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_start_stop_no_vacation_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_start_stop_no_vacation.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'jam_error', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_jam_error_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_jam_error.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'jam_inactive', 'MG32401A2US100204', 57, 16, 22, 12, 12, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_jam_inactive_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_jam_inactive.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'empty_bucket', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~3hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_empty_bucket_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_empty_bucket.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'heat_warning_status', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_heat_warning_status_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_heat_warning_status.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', 'hip', 'qa9', 'hip_moisture_food_add', 'MG32401A2US100204', 57, 16, 22, 10, 10, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_dgo_hip_moisture_food_add_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_hip_moisture_food_add.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'cooldown_temp', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_bat_cooldown_temp_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_cooldown_temp.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'heat_led', 'MG32401A2US100204', 57, 16, 22, 22, 22, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_bat_heat_led_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_heat_led.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'premature_mass_no_reset', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_premature_mass_no_reset_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_premature_mass_no_reset.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'locked_when_hot_shadows', 'MG32401A2US100204', 57, 16, 22, 11, 11, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_locked_when_hot_shadows_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_locked_when_hot_shadows.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'vacation_clean_mode', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_clean_mode_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_vacation_clean_mode.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'vacation_eco_mode', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_eco_mode_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_vacation_eco_mode.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'vacation_add_mass_cooldown', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_add_mass_cooldown_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_vacation_add_mass_cooldown.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'vacation_reset', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_reset_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_vacation_reset.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'grinder_soft_stall_retry', 'MG32401A2US100204', 57, 16, 22, 11, 11, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_grinder_soft_stall_retry_same_dir_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_grinder_soft_stall_retry.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'grinder_state_lid', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_grinder_state_lid_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_grinder_state_lid.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'grinder_high_temp_jam', 'MG32401A2US100204', 57, 16, 22, 14, 14, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_grinder_high_temp_jam_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_grinder_high_temp_jam.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'grinder_jam_auto_retry', 'MG32401A2US100204', 57, 16, 22, 11, 11, 0, '~1.5hrs', 1, '', false, '', false, '', false, './O2_bat_grinder_jam_auto_retry_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_grinder_jam_auto_retry.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'fluff_not_run', 'MG32401A2US100204', 57, 16, 22, 8, 8, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_fluff_not_run_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_fluff_not_run.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'always_locked', 'MG32401A2US100204', 57, 16, 22, 10, 10, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_always_locked_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_always_locked.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'always_unlocked', 'MG32401A2US100204', 57, 16, 22, 15, 15, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_always_unlocked_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_always_unlocked.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'bucket_fullness_low', 'MG32401A2US100204', 57, 16, 22, 4, 4, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_bucket_fullness_detection_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_bucket_fullness_low.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'locked_when_running', 'MG32401A2US100204', 57, 16, 22, 16, 16, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_locked_when_running_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_locked_when_running.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'fr_heat_warning_status', 'MG32401A2US100204', 57, 16, 22, 17, 17, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_fr_heat_warning_status_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_fr_heat_warning_status.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'dgo_hip_mass_bucket', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~3.5hrs', 1, '', false, '', false, '', false, './O2_bat_delta_mr_mass_bucket_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_hip_mass_bucket.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'resume_lip', 'MG32401A2US100204', 57, 16, 22, 7, 7, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_resume_from_lip_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_resume_lip.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'cycle_start_time_HIP', 'MG32401A2US100204', 57, 16, 22, 11, 11, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_set_dgo_start_time_during_hip_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/dgo_set_cycle_start_time_HIP_O2.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'unprocessed_mass_zero', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_unprocessed_mass_zero_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_unprocessed_mass_zero.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'mass_add_lid_open_close', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_mass_add_lid_open_close_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_mass_add_lid_open_close.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'mass_no_change_reset', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_mass_no_change_reset_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_mass_no_change_reset.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'locked_when_running', 'MG32401A2US100204', 57, 16, 22, 16, 16, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_locked_when_running_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_locked_when_running.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'lastdgocycle_energy_shadows', 'MG32401A2US100204', 57, 16, 22, 14, 14, 0, '~4.5hrs', 1, '', false, '', false, '', false, './O2_bat_lastDgoCycle_energy_shadows_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_lastDgoCycle_energy_shadows.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'cycleendtime_lid_open', 'MG32401A2US100204', 57, 16, 22, 9, 9, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_cycleEndTime_lid_open_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_cycleEndTime_lid_open.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'lip_skipped_hot', 'MG32401A2US100204', 57, 16, 22, 14, 14, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_bat_lip_skipped_hot_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_lip_skipped_hot.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'hip_extension_lid_open_close', 'MG32401A2US100204', 57, 16, 22, 18, 18, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_hip_extension_lid_open_close_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_hip_extension_lid_open_close.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'start_disconnected', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_start_disconnected_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_start_disconnected.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'resume_disconnected', 'MG32401A2US100204', 57, 16, 22, 13, 13, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_resume_disconnected_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_resume_disconnected.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'heat_led_interruptions', 'MG32401A2US100204', 57, 16, 22, 18, 18, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_heat_led_interruptions_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_heat_led_interruptions.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'vacation_after_empty', 'MG32401A2US100204', 57, 16, 22, 6, 6, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_after_empty_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_vacation_after_empty.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'resume_cooldown', 'MG32401A2US100204', 57, 16, 22, 22, 22, 0, '~1hrs', 1, '', false, '', false, '', false, './O2_bat_resume_cooldown_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_dgo_resume_cooldown.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'bat_vacation_ota_pre', 'MG32401A2US100204', 57, 16, 22, 10, 10, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_ota_pre_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_vacation_ota_pre.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'bat_vacation_ota_post', 'MG32401A2US100204', 57, 16, 22, 2, 2, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_vacation_ota_post_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_vacation_ota_post.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'bat_bucket_crash_ota_pre', 'MG32401A2US100204', 57, 16, 22, 6, 6, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_bucket_crash_ota_pre_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_bucket_crash_ota_pre.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

TABLE_NAME="BAT_TABLE"
COLUMN_NAMES="(TemplateN, OscarType, Stage, SvrName, Type, ThingSN, OscarId, SvrId, DeviceId, TestExecuted, Passed, Failed, ExeTime, Repeats, Jira1, JiraF1, Jira2, JiraF2, Jira3, JiraF3, ResultLink, TestCasesLink, DebugLink, Notes)" 
VALUES="('dbg-v02_00_03-9b5d04e', 'O2', '', 'qa9', 'bat_bucket_crash_ota_post', 'MG32401A2US100204', 57, 16, 22, 2, 2, 0, '~0.5hrs', 1, '', false, '', false, '', false, './O2_bat_bucket_crash_ota_post_results_v02_00_03.txt', 'https://github.com/chewielabs/Oscar-Python-CLI/blob/main/src/oscar/dgo/testsuites/bat_bucket_crash_ota_post.json', '', '')"
QUERY="INSERT INTO $TABLE_NAME $COLUMN_NAMES VALUES $VALUES;"
psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "$QUERY"

unset PGPASSWORD
